---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  data_bags_path: ./test/data_bags

platforms:
  - name: ubuntu-14.04
  - name: centos-6.4

suites:
  - name: default
    run_list: ["recipe[madison-server]"]
    attributes:
