name             'madison-server'
maintainer       'The OpenGov Foundation'
maintainer_email 'developers@opengovfoundation.org'
license          'CC0'
description      'Installs/Configures madison-server'
long_description 'Installs/Configures madison-server'
version          '0.1.25'

depends 'git'
depends 'opengov-users', '0.1.8'
depends 'lamp-server', '0.1.26'
depends 'composer'
